# chain for the robot arm
rebel_arm:
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_search_resolution: 0.0001
    kinematics_solver_timeout: 0.005
    kinematics_solver_attempts: 5000

    # alternative inverse kinematics solver
    # kinematics_solver: pick_ik/PickIkPlugin
    # kinematics_solver_timeout: 0.01
    # kinematics_solver_attempts: 10000
    # mode: global
    # position_scale: 1.0
    # rotation_scale: 0.5
    # position_threshold: 0.0005
    # orientation_threshold: 0.001
