# MoveIt uses this configuration for controller management
trajectory_execution:
    allowed_execution_duration_scaling: 1.2 # multiplicative factor applied to get allowed duration of trajectory execution
    allowed_goal_duration_margin: 0.5 # multiplicative facvtor applied to allow more than the expected execution time
    allowed_start_tolerance: 0.05 # joint-value tolerance in radians for validating trajectory's start point against current state
    trajectory_duration_monitoring: true
    moveit_manage_controllers: true

#/**:
#  ros__parameters:
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
#ros__parameters:
    controller_names:
        - rebel_arm_controller

    rebel_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6