# This config file is used by ros2_control
controller_manager:
    ros__parameters:
        update_rate: 50 # Hz

        rebel_arm_controller:
            type: "joint_trajectory_controller/JointTrajectoryController"

        joint_state_broadcaster:
            type: "joint_state_broadcaster/JointStateBroadcaster"

        #gripper_controller:
            #type: position_controllers/GripperActionController


rebel_arm_controller:
    ros__parameters:
        joints:
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
        command_interfaces: # controller output
            #- position # simmply forwards joint angles position commands to the hardware
            - velocity # uses PID regulator internally unless open_loop_control is true
            #- effort # torque -> works like velocity control via PID loop
        state_interfaces: # controller input
            - position
            - velocity
        state_publish_rate: 50.0
        open_loop_control: true # if true, the controller does not use PID regulator
        constraints:
            stopped_velocity_tolerance: 0.05
        action_monitor_rate: 25.0
