# This config file is used by ros2_control
controller_manager:
    ros__parameters:
        update_rate: 50 # Hz

        rebel_arm_controller:
            type: "joint_trajectory_controller/JointTrajectoryController"

        joint_state_broadcaster:
            type: "joint_state_broadcaster/JointStateBroadcaster"

        #gripper_controller:
            #type: position_controllers/GripperActionController

# joint trajectory controller configuration parameters documentation
# https://control.ros.org/iron/doc/ros2_controllers/joint_trajectory_controller/doc/parameters.html

rebel_arm_controller:
    ros__parameters:
        joints:
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
        
        command_interfaces: # controller output
            #- position # simmply forwards joint angles position commands to the hardware
            - velocity # uses PID regulator internally unless open_loop_control is true
            #- effort # torque -> works like velocity control via PID loop
        state_interfaces: # controller input
            - position
            - velocity
        open_loop_control: true # if true, the controller does not use PID regulator
        action_monitor_rate: 35.0
        allow_nonzero_velocity_at_trajectory_end: true # false doesn't work with current implementation of the controller
        constraints:
            stopped_velocity_tolerance: 0.01

        # gains structure working well in simulation, proof tested with plotjuggler
        # NOT WORKING WITH REAL ROBOT
        #gains:
        #    joint1: { p: 10.0, i: 0.01, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
        #    joint2: { p: 10.0, i: 0.01, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
        #    joint3: { p: 10.0, i: 0.01, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
        #    joint4: { p: 10.0, i: 0.01, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
        #    joint5: { p: 10.0, i: 0.01, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
        #    joint6: { p: 10.0, i: 0.01, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}

        gains:
            joint1: { p: 2.0, i: 0.1, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
            joint2: { p: 2.0, i: 0.1, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
            joint3: { p: 2.0, i: 0.1, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
            joint4: { p: 2.0, i: 0.1, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
            joint5: { p: 2.0, i: 0.1, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
            joint6: { p: 2.0, i: 0.1, d: 0.01, i_clamp: 100.0, ff_velocity_scale: 0.5}
